##############
# gosdir.com #
##############
<VirtualHost 204.109.58.162:80>
    Include etc/apache24/logs.conf

    ServerAdmin webmaster@gosdir.com
    ServerName gosdir.com
    ServerAlias www.gosdir.com
    DocumentRoot "/usr/web/gosdir.com"

    ErrorLog /var/log/httpd/gosdir.com-error.log
    CustomLog /var/log/httpd/gosdir.com-access.log combined

    <Directory "/usr/web/gosdir.com">
        Options -Indexes
        DirectoryIndex index.html
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost 204.109.58.162:443>
    ServerAdmin webmaster@gosdir.com
    ServerName gosdir.com
    ServerAlias www.gosdir.com
    DocumentRoot "/usr/web/gosdir.com"

    ErrorLog /var/log/httpd/gosdir.com-ssl-error.log
    CustomLog /var/log/httpd/gosdir.com-ssl-access.log combined

    SSLEngine on
    SSLCertificateFile "/usr/local/etc/letsencrypt/live/gosdir.com/fullchain.pem"
    SSLCertificateKeyFile "/usr/local/etc/letsencrypt/live/gosdir.com/privkey.pem"

    <Directory "/usr/web/gosdir.com">
        Options -Indexes
        DirectoryIndex index.html
        Require all granted
    </Directory>
</VirtualHost>
