import type { Agency } from './types';

export const agencies: Agency[] = [
  {
    id: 'us-gsa',
    name: 'General Services Administration',
    abbreviation: 'GSA',
    aliases: ['U.S. General Services Administration'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.gsa.gov/',
  },
  {
    id: 'us-dod',
    name: 'Department of Defense',
    abbreviation: 'DOD',
    aliases: ['DoD', 'U.S. Department of Defense'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.defense.gov/',
  },
  {
    id: 'us-nasa',
    name: 'National Aeronautics and Space Administration',
    abbreviation: 'NASA',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.nasa.gov/',
  },
  {
    id: 'us-doc',
    name: 'Department of Commerce',
    abbreviation: 'DOC',
    aliases: ['U.S. Department of Commerce'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.commerce.gov/',
  },
  {
    id: 'us-nist',
    name: 'National Institute of Standards and Technology',
    abbreviation: 'NIST',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.nist.gov/',
    parentAgencyId: 'us-doc',
  },
  {
    id: 'us-doe',
    name: 'Department of Energy',
    abbreviation: 'DOE',
    aliases: ['U.S. Department of Energy'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.energy.gov/',
  },
  {
    id: 'us-va',
    name: 'Department of Veterans Affairs',
    abbreviation: 'VA',
    aliases: ['U.S. Department of Veterans Affairs', 'Veterans Affairs'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.va.gov/',
  },
  {
    id: 'us-hhs',
    name: 'Department of Health and Human Services',
    abbreviation: 'HHS',
    aliases: ['U.S. Department of Health and Human Services'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.hhs.gov/',
  },
  {
    id: 'us-usda',
    name: 'Department of Agriculture',
    abbreviation: 'USDA',
    aliases: ['U.S. Department of Agriculture'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.usda.gov/',
  },
  {
    id: 'us-dhs',
    name: 'Department of Homeland Security',
    abbreviation: 'DHS',
    aliases: ['U.S. Department of Homeland Security'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.dhs.gov/',
  },
  {
    id: 'us-doi',
    name: 'Department of the Interior',
    abbreviation: 'DOI',
    aliases: ['U.S. Department of the Interior'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.doi.gov/',
  },
  {
    id: 'us-doj',
    name: 'Department of Justice',
    abbreviation: 'DOJ',
    aliases: ['U.S. Department of Justice'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.justice.gov/',
  },
  {
    id: 'us-dol',
    name: 'Department of Labor',
    abbreviation: 'DOL',
    aliases: ['U.S. Department of Labor'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.dol.gov/',
  },
  {
    id: 'us-ed',
    name: 'Department of Education',
    abbreviation: 'ED',
    aliases: ['U.S. Department of Education'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.ed.gov/',
  },
  {
    id: 'us-epa',
    name: 'Environmental Protection Agency',
    abbreviation: 'EPA',
    aliases: ['U.S. Environmental Protection Agency'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.epa.gov/',
  },
  {
    id: 'us-state',
    name: 'Department of State',
    abbreviation: 'STATE',
    aliases: ['DOS', 'State Department', 'U.S. Department of State'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Department',
    officialUrl: 'https://www.state.gov/',
  },
  {
    id: 'us-army',
    name: 'United States Army',
    abbreviation: 'U.S. Army',
    aliases: ['Army'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Military service',
    officialUrl: 'https://www.army.mil/',
    parentAgencyId: 'us-dod',
  },
  {
    id: 'us-army-research-laboratory',
    name: 'U.S. Army Research Laboratory',
    abbreviation: 'ARL',
    aliases: ['DEVCOM Army Research Laboratory'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Laboratory',
    officialUrl: 'https://arl.devcom.army.mil/',
    parentAgencyId: 'us-army',
  },
  {
    id: 'us-army-devcom-c5isr-center',
    name: 'U.S. Army Combat Capabilities Development Command C5ISR Center',
    abbreviation: 'DEVCOM C5ISR Center',
    aliases: ['Army DEVCOM C5ISR', 'C5ISR Center'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.c5isrcenter.army.mil/',
    parentAgencyId: 'us-army',
  },
  {
    id: 'us-tak-product-center',
    name: 'TAK Product Center',
    abbreviation: 'TPC',
    aliases: ['Tactical Assault Kit Product Center'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Office',
    officialUrl: 'https://tak.gov/',
    parentAgencyId: 'us-army-devcom-c5isr-center',
  },
  {
    id: 'us-air-force',
    name: 'United States Air Force',
    abbreviation: 'USAF',
    aliases: ['U.S. Air Force', 'Air Force'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Military service',
    officialUrl: 'https://www.af.mil/',
    parentAgencyId: 'us-dod',
  },
  {
    id: 'us-air-force-research-laboratory',
    name: 'Air Force Research Laboratory',
    abbreviation: 'AFRL',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Laboratory',
    officialUrl: 'https://www.afrl.af.mil/',
    parentAgencyId: 'us-air-force',
  },
  {
    id: 'us-nsa',
    name: 'National Security Agency',
    abbreviation: 'NSA',
    aliases: ['NSA Cybersecurity'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.nsa.gov/',
    parentAgencyId: 'us-dod',
  },
  {
    id: 'us-nga',
    name: 'National Geospatial-Intelligence Agency',
    abbreviation: 'NGA',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.nga.mil/',
    parentAgencyId: 'us-dod',
  },
  {
    id: 'us-army-corps-of-engineers',
    name: 'U.S. Army Corps of Engineers',
    abbreviation: 'USACE',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Agency',
    officialUrl: 'https://www.usace.army.mil/',
    parentAgencyId: 'us-army',
  },
  {
    id: 'us-army-erdc',
    name: 'U.S. Army Engineer Research and Development Center',
    abbreviation: 'ERDC',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Laboratory',
    officialUrl: 'https://www.erdc.usace.army.mil/',
    parentAgencyId: 'us-army-corps-of-engineers',
  },
  {
    id: 'us-army-cerl',
    name: 'Construction Engineering Research Laboratory',
    abbreviation: 'CERL',
    aliases: ['U.S. Army CERL'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    type: 'Laboratory',
    officialUrl: 'https://www.erdc.usace.army.mil/Locations/CERL/',
    parentAgencyId: 'us-army-erdc',
  },
  {
    id: 'us-ca-government',
    name: 'State of California',
    aliases: ['California state government'],
    geography: 'California',
    jurisdiction: 'U.S. state',
    type: 'Government',
    officialUrl: 'https://www.ca.gov/',
  },
  {
    id: 'us-ca-cdt',
    name: 'California Department of Technology',
    abbreviation: 'CDT',
    geography: 'California',
    jurisdiction: 'U.S. state',
    type: 'Department',
    officialUrl: 'https://cdt.ca.gov/',
    parentAgencyId: 'us-ca-government',
  },
  {
    id: 'us-ma-commonwealth',
    name: 'Commonwealth of Massachusetts',
    aliases: ['Massachusetts state government'],
    geography: 'Massachusetts',
    jurisdiction: 'U.S. state',
    type: 'Government',
    officialUrl: 'https://www.mass.gov/',
  },
  {
    id: 'uk-government',
    name: 'Government of the United Kingdom',
    aliases: ['UK Government'],
    geography: 'United Kingdom',
    jurisdiction: 'International',
    type: 'Government',
    officialUrl: 'https://www.gov.uk/',
  },
  {
    id: 'uk-cabinet-office',
    name: 'Cabinet Office',
    aliases: ['UK Cabinet Office'],
    geography: 'United Kingdom',
    jurisdiction: 'International',
    type: 'Department',
    officialUrl: 'https://www.gov.uk/government/organisations/cabinet-office',
    parentAgencyId: 'uk-government',
  },
  {
    id: 'uk-government-digital-service',
    name: 'Government Digital Service',
    abbreviation: 'GDS',
    aliases: ['UK Government Digital Service'],
    geography: 'United Kingdom',
    jurisdiction: 'International',
    type: 'Agency',
    officialUrl:
      'https://www.gov.uk/government/organisations/government-digital-service',
    parentAgencyId: 'uk-cabinet-office',
  },
  {
    id: 'ee-government',
    name: 'Government of Estonia',
    aliases: ['Estonian government'],
    geography: 'Estonia',
    jurisdiction: 'International',
    type: 'Government',
    officialUrl: 'https://www.valitsus.ee/en',
  },
  {
    id: 'fi-government',
    name: 'Government of Finland',
    aliases: ['Finnish government'],
    geography: 'Finland',
    jurisdiction: 'International',
    type: 'Government',
    officialUrl: 'https://valtioneuvosto.fi/en/frontpage',
  },
  {
    id: 'ee-fi-niis',
    name: 'Nordic Institute for Interoperability Solutions',
    abbreviation: 'NIIS',
    geography: 'Estonia and Finland',
    jurisdiction: 'International',
    type: 'Public body',
    officialUrl: 'https://www.niis.org/',
  },
  {
    id: 'sg-govtech',
    name: 'Government Technology Agency of Singapore',
    abbreviation: 'GovTech Singapore',
    aliases: ['GovTech'],
    geography: 'Singapore',
    jurisdiction: 'International',
    type: 'Agency',
    officialUrl: 'https://www.tech.gov.sg/',
  },
  {
    id: 'fr-dinum',
    name: 'French Interministerial Digital Directorate',
    abbreviation: 'DINUM',
    aliases: ['Direction interministérielle du numérique'],
    geography: 'France',
    jurisdiction: 'International',
    type: 'Agency',
    officialUrl: 'https://www.numerique.gouv.fr/',
  },
  {
    id: 'es-barcelona-city-council',
    name: 'Barcelona City Council',
    aliases: ['Ajuntament de Barcelona'],
    geography: 'Spain',
    jurisdiction: 'International',
    type: 'Government',
    officialUrl: 'https://www.barcelona.cat/en/',
  },
  {
    id: 'ca-canadian-digital-service',
    name: 'Canadian Digital Service',
    abbreviation: 'CDS',
    aliases: ['Service numérique canadien'],
    geography: 'Canada',
    jurisdiction: 'International',
    type: 'Agency',
    officialUrl: 'https://digital.canada.ca/',
  },
];
