import type { Project } from './types';

export const projects: Project[] = [
  {
    id: 'uswds',
    name: 'U.S. Web Design System',
    summary:
      'Accessible components, design tokens, and guidance for trustworthy federal digital services.',
    sponsor: 'General Services Administration',
    agencyIds: ['us-gsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Design systems',
    license: 'Public domain / CC0',
    repository: 'https://github.com/uswds/uswds',
    officialUrl: 'https://designsystem.digital.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['accessibility', 'design', 'web'],
  },
  {
    id: 'login-gov',
    name: 'Login.gov',
    summary:
      'A shared sign-in service that gives the public simple, secure access to participating U.S. government programs.',
    sponsor: 'General Services Administration',
    agencyIds: ['us-gsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Digital identity',
    license: 'Public domain / CC0',
    repository: 'https://github.com/18F/identity-idp',
    officialUrl: 'https://www.login.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['identity', 'security', 'shared service'],
  },
  {
    id: 'cloud-gov',
    name: 'cloud.gov',
    summary:
      'A secure, compliant platform that helps U.S. agencies deliver applications without rebuilding cloud infrastructure.',
    sponsor: 'General Services Administration',
    agencyIds: ['us-gsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cloud platform',
    license: 'Public domain / CC0',
    repository: 'https://github.com/cloud-gov',
    officialUrl: 'https://cloud.gov/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['cloud', 'platform', 'security'],
  },
  {
    id: 'code-gov',
    name: 'Code.gov',
    summary:
      'The federal source-code policy program and public inventory work created to improve discoverability and reuse.',
    sponsor: 'General Services Administration',
    agencyIds: ['us-gsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Code inventory',
    license: 'Public domain',
    repository: 'https://github.com/GSA/code-gov',
    officialUrl: 'https://code.gov/',
    status: 'Reference',
    verified: '2026-09-03',
    tags: ['inventory', 'policy', 'reuse'],
  },
  {
    id: 'oscal',
    name: 'OSCAL',
    summary:
      'Machine-readable formats from NIST for expressing system security controls, assessments, and plans.',
    sponsor: 'National Institute of Standards and Technology',
    agencyIds: ['us-nist'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cybersecurity',
    license: 'Public domain',
    repository: 'https://github.com/usnistgov/OSCAL',
    officialUrl: 'https://pages.nist.gov/OSCAL/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['security', 'standards', 'compliance'],
  },
  {
    id: 'openmdao',
    name: 'OpenMDAO',
    summary:
      'A NASA-developed multidisciplinary design, analysis, and optimization framework for complex engineering systems.',
    sponsor: 'National Aeronautics and Space Administration',
    agencyIds: ['us-nasa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Science & engineering',
    license: 'Apache-2.0',
    repository: 'https://github.com/OpenMDAO/OpenMDAO',
    officialUrl: 'https://openmdao.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['aerospace', 'optimization', 'science'],
  },
  {
    id: 'energyplus',
    name: 'EnergyPlus',
    summary:
      'A whole-building energy simulation engine maintained with support from the U.S. Department of Energy.',
    sponsor: 'Department of Energy',
    agencyIds: ['us-doe'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Climate & energy',
    license: 'BSD-3-Clause',
    repository: 'https://github.com/NREL/EnergyPlus',
    officialUrl: 'https://energyplus.net/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['buildings', 'energy', 'simulation'],
  },
  {
    id: 'vets-api',
    name: 'VA.gov Vets API',
    summary:
      'The API platform that powers veteran-facing services and integrations across VA.gov.',
    sponsor: 'Department of Veterans Affairs',
    agencyIds: ['us-va'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Public benefits',
    license: 'CC0-1.0',
    repository: 'https://github.com/department-of-veterans-affairs/vets-api',
    officialUrl: 'https://developer.va.gov/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['veterans', 'api', 'benefits'],
  },
  {
    id: 'code-mil',
    name: 'Code.mil',
    summary:
      'The Department of Defense initiative for open collaboration and guidance around releasing government code.',
    sponsor: 'Department of Defense',
    agencyIds: ['us-dod'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Code inventory',
    license: 'Public domain / OSI licenses',
    repository: 'https://github.com/Code-dot-mil',
    officialUrl: 'https://code.mil/',
    status: 'Maintained',
    featured: true,
    verified: '2026-09-03',
    tags: ['defense', 'policy', 'collaboration'],
  },
  {
    id: 'ca-design-system',
    name: 'California Design System',
    summary:
      'Reusable patterns and components for consistent, accessible State of California digital services.',
    sponsor: 'California Department of Technology',
    agencyIds: ['us-ca-cdt'],
    geography: 'California',
    jurisdiction: 'U.S. state',
    domain: 'Design systems',
    license: 'Apache-2.0',
    repository: 'https://github.com/cagov/design-system',
    officialUrl: 'https://designsystem.webstandards.ca.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['california', 'accessibility', 'design'],
  },
  {
    id: 'mayflower',
    name: 'Mayflower',
    summary:
      'The component library and pattern system created for Mass.gov digital products.',
    sponsor: 'Commonwealth of Massachusetts',
    agencyIds: ['us-ma-commonwealth'],
    geography: 'Massachusetts',
    jurisdiction: 'U.S. state',
    domain: 'Design systems',
    license: 'MIT',
    repository: 'https://github.com/massgov/mayflower',
    officialUrl: 'https://mayflower.digital.mass.gov/',
    status: 'Maintained',
    verified: '2026-09-03',
    tags: ['massachusetts', 'design', 'web'],
  },
  {
    id: 'govuk-design-system',
    name: 'GOV.UK Design System',
    summary:
      'A mature library of styles, components, and patterns used to build consistent UK public services.',
    sponsor: 'UK Government Digital Service',
    agencyIds: ['uk-government-digital-service'],
    geography: 'United Kingdom',
    jurisdiction: 'International',
    domain: 'Design systems',
    license: 'MIT',
    repository: 'https://github.com/alphagov/govuk-frontend',
    officialUrl: 'https://design-system.service.gov.uk/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['united kingdom', 'design', 'accessibility'],
  },
  {
    id: 'govuk-notify',
    name: 'GOV.UK Notify',
    summary:
      'A reusable notification service for public-sector email, text messages, and letters.',
    sponsor: 'UK Government Digital Service',
    agencyIds: ['uk-government-digital-service'],
    geography: 'United Kingdom',
    jurisdiction: 'International',
    domain: 'Communications',
    license: 'MIT',
    repository: 'https://github.com/alphagov/notifications-api',
    officialUrl: 'https://www.notifications.service.gov.uk/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['united kingdom', 'notifications', 'shared service'],
  },
  {
    id: 'x-road',
    name: 'X-Road',
    summary:
      'The secure data exchange layer established by Estonia and Finland and now reused internationally.',
    sponsor: 'Estonia & Finland / NIIS',
    agencyIds: ['ee-government', 'fi-government', 'ee-fi-niis'],
    geography: 'Estonia',
    jurisdiction: 'International',
    domain: 'Data exchange',
    license: 'MIT',
    repository: 'https://github.com/nordic-institute/X-Road',
    officialUrl: 'https://x-road.global/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['estonia', 'finland', 'interoperability'],
  },
  {
    id: 'formsg',
    name: 'FormSG',
    summary:
      'A secure form builder built and maintained by Singapore’s Open Government Products team.',
    sponsor: 'Government Technology Agency of Singapore',
    agencyIds: ['sg-govtech'],
    geography: 'Singapore',
    jurisdiction: 'International',
    domain: 'Forms & workflows',
    license: 'MIT',
    repository: 'https://github.com/opengovsg/FormSG',
    officialUrl: 'https://form.gov.sg/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['singapore', 'forms', 'productivity'],
  },
  {
    id: 'openfisca',
    name: 'OpenFisca',
    summary:
      'A rules-as-code engine initiated in France for modeling taxes and benefits as testable software.',
    sponsor: 'French Interministerial Digital Directorate',
    agencyIds: ['fr-dinum'],
    geography: 'France',
    jurisdiction: 'International',
    domain: 'Rules as code',
    license: 'AGPL-3.0',
    repository: 'https://github.com/openfisca/openfisca-core',
    officialUrl: 'https://openfisca.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['france', 'benefits', 'policy'],
  },
  {
    id: 'decidim',
    name: 'Decidim',
    summary:
      'A participatory democracy platform initiated by Barcelona and governed as a digital public commons.',
    sponsor: 'Barcelona City Council',
    agencyIds: ['es-barcelona-city-council'],
    geography: 'Spain',
    jurisdiction: 'International',
    domain: 'Civic participation',
    license: 'AGPL-3.0',
    repository: 'https://github.com/decidim/decidim',
    officialUrl: 'https://decidim.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['spain', 'democracy', 'participation'],
  },
  {
    id: 'gc-notify',
    name: 'GC Notify',
    summary:
      'Canada’s government notification service for sending reliable email and text messages at scale.',
    sponsor: 'Canadian Digital Service',
    agencyIds: ['ca-canadian-digital-service'],
    geography: 'Canada',
    jurisdiction: 'International',
    domain: 'Communications',
    license: 'MIT',
    repository: 'https://github.com/cds-snc/notification-api',
    officialUrl: 'https://notification.canada.ca/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['canada', 'notifications', 'shared service'],
  },
  {
    id: 'brl-cad',
    name: 'BRL-CAD',
    summary:
      'A long-running constructive solid geometry modeling, editing, ray-tracing, and analysis system created by the U.S. Army and developed in the open since 2004.',
    sponsor: 'U.S. Army Research Laboratory',
    agencyIds: ['us-army-research-laboratory'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: '3D modeling',
    license:
      'LGPL-2.1 collective work; component-specific BSD/BDL/Public domain/third-party terms',
    repository: 'https://github.com/BRL-CAD/brlcad',
    officialUrl: 'https://brlcad.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: '2026-09-12',
    tags: ['army', 'cad', 'geometry', 'modeling', 'simulation'],
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    summary:
      'A software reverse-engineering framework developed by NSA Research and released publicly as open source in 2019.',
    sponsor: 'National Security Agency',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Software analysis',
    license:
      'Apache-2.0 primary; GPL-3.0 support programs; federal portions Public domain; third-party terms',
    repository: 'https://github.com/NationalSecurityAgency/ghidra',
    officialUrl: 'https://www.nsa.gov/ghidra',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: '2026-09-12',
    tags: ['nsa', 'cybersecurity', 'reverse engineering', 'analysis'],
  },
  {
    id: 'atak-civ',
    name: 'Android Tactical Assault Kit for Civilian Use (ATAK-CIV)',
    summary:
      'The open source civilian edition of a government-owned geospatial situational-awareness platform; the record does not imply that every TAK product line is open source.',
    sponsor:
      'TAK Product Center / Army DEVCOM C5ISR; Air Force Research Laboratory (origin)',
    agencyIds: [
      'us-tak-product-center',
      'us-army-devcom-c5isr-center',
      'us-air-force-research-laboratory',
    ],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Situational awareness',
    license: 'GPL-3.0; qualifying U.S. federal portions Public domain',
    repository: 'https://github.com/TAK-Product-Center/atak-civ',
    officialUrl: 'https://tak.gov/pages/our-process',
    evidenceUrl: 'https://afresearchlab.com/tactical-assault-kit-tak/',
    status: 'Active',
    featured: true,
    verified: '2026-09-12',
    tags: ['air force', 'geospatial', 'public safety', 'mobile'],
  },
  {
    id: 'hirs',
    name: 'HIRS',
    summary:
      'An NSA proof-of-concept for trusted-computing provisioning, platform integrity reporting, and hardware attestation; its repository warns that it is not production-ready.',
    sponsor: 'NSA Cybersecurity',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Supply chain security',
    license: 'Apache-2.0 / Public domain',
    repository: 'https://github.com/nsacyber/HIRS',
    officialUrl: 'https://github.com/nsacyber/HIRS',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Reference',
    verified: '2026-09-12',
    tags: ['nsa', 'hardware', 'attestation', 'tpm', 'experimental'],
  },
  {
    id: 'paccor',
    name: 'paccor',
    summary:
      'NSA tooling for creating, signing, inspecting, and validating platform attribute certificates used in hardware and software supply-chain attestation.',
    sponsor: 'NSA Cybersecurity',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Supply chain security',
    license: 'Apache-2.0',
    repository: 'https://github.com/nsacyber/paccor',
    officialUrl: 'https://nsacyber.github.io/paccor/',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nsa', 'hardware', 'attestation', 'certificates'],
  },
  {
    id: 'hootenanny',
    name: 'Hootenanny',
    summary:
      'A machine-assisted map-conflation and schema-translation system funded by NGA, open-sourced in 2015, and used in government geospatial production.',
    sponsor: 'National Geospatial-Intelligence Agency',
    agencyIds: ['us-nga'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'GPL-3.0',
    repository: 'https://github.com/ngageoint/hootenanny',
    officialUrl:
      'https://github.com/ngageoint/hootenanny/blob/master/docs/overview/Introduction.asciidoc',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nga', 'maps', 'conflation', 'geospatial'],
  },
  {
    id: 'mage',
    name: 'MAGE',
    summary:
      'A mobile field-data collection and situational-awareness platform designed for low-bandwidth and disconnected environments.',
    sponsor: 'National Geospatial-Intelligence Agency',
    agencyIds: ['us-nga'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Field data',
    license: 'Apache-2.0',
    repository: 'https://github.com/ngageoint/MAGE',
    officialUrl: 'https://www.nga.mil/assets/files/2024_MAGE_Fact_Sheet.pdf',
    evidenceUrl: 'https://github.com/ngageoint/MAGE',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nga', 'mobile', 'geospatial', 'offline'],
  },
  {
    id: 'sarpy',
    name: 'SarPy',
    summary:
      'An NGA-developed Python library for synthetic-aperture-radar and geospatial data; the repository is consolidating toward SARKit and flags legacy-reader deprecations for SarPy 2.0.',
    sponsor: 'National Geospatial-Intelligence Agency',
    agencyIds: ['us-nga'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'MIT',
    repository: 'https://github.com/ngageoint/sarpy',
    officialUrl: 'https://github.com/ngageoint/sarpy',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nga', 'radar', 'imagery', 'python'],
  },
  {
    id: 'nga-geopackage',
    name: 'NGA GeoPackage',
    summary:
      'A suite of NGA software development kits for standards-based geospatial storage; the project remains available but is in maintenance mode.',
    sponsor: 'National Geospatial-Intelligence Agency',
    agencyIds: ['us-nga'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'MIT',
    repository: 'https://github.com/ngageoint/GeoPackage',
    officialUrl: 'https://github.com/ngageoint/GeoPackage',
    status: 'Maintained',
    verified: '2026-09-12',
    tags: ['nga', 'geopackage', 'sdk', 'maintenance mode'],
  },
  {
    id: 'apache-accumulo',
    name: 'Apache Accumulo',
    summary:
      'A distributed sorted key-value store with cell-level security, begun at NSA in 2008 and transferred to independent Apache Software Foundation governance.',
    sponsor: 'Apache Software Foundation; National Security Agency (origin)',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Data infrastructure',
    license: 'Apache-2.0',
    repository: 'https://github.com/apache/accumulo',
    officialUrl: 'https://accumulo.apache.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: '2026-09-12',
    tags: ['nsa', 'apache', 'database', 'security'],
  },
  {
    id: 'apache-nifi',
    name: 'Apache NiFi',
    summary:
      'A secure dataflow automation platform that originated at NSA as NiagaraFiles and moved to independent Apache Software Foundation governance in 2014.',
    sponsor: 'Apache Software Foundation; National Security Agency (origin)',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Data integration',
    license: 'Apache-2.0',
    repository: 'https://github.com/apache/nifi',
    officialUrl: 'https://nifi.apache.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nsa', 'apache', 'dataflow', 'provenance'],
  },
  {
    id: 'grass-gis',
    name: 'GRASS GIS',
    summary:
      'A four-decade geospatial analysis platform created by the U.S. Army Corps of Engineers and now sustained as an OSGeo community project.',
    sponsor: 'OSGeo / NumFOCUS; U.S. Army CERL (origin)',
    agencyIds: ['us-army-cerl'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'GPL-2.0-or-later',
    repository: 'https://github.com/OSGeo/grass',
    officialUrl: 'https://grass.osgeo.org/about/history/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['army corps', 'osgeo', 'gis', 'maps'],
  },
  {
    id: 'paraview',
    name: 'ParaView',
    summary:
      'A distributed scientific-visualization application developed through collaboration among Kitware, national laboratories, the Department of Energy, and Army Research Laboratory.',
    sponsor:
      'Kitware; DOE national laboratories and U.S. Army Research Laboratory collaborators',
    agencyIds: ['us-doe', 'us-army-research-laboratory'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Science & engineering',
    license: 'BSD-3-Clause',
    repository: 'https://gitlab.kitware.com/paraview/paraview',
    officialUrl: 'https://www.paraview.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['doe', 'army', 'visualization', 'science'],
  },
  {
    id: 'selinux',
    name: 'SELinux',
    summary:
      'The userspace tools and libraries for the NSA-origin SELinux mandatory-access-control architecture, now maintained by the broader SELinux community.',
    sponsor: 'SELinux community; National Security Agency (origin)',
    agencyIds: ['us-nsa'],
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cybersecurity',
    license:
      'Mixed, component-specific GPL-2.0/LGPL-2.1/Public domain/FreeBSD/third-party terms',
    repository: 'https://github.com/SELinuxProject/selinux',
    officialUrl:
      'https://www.nsa.gov/Research/NSA-Mission-Oriented-Research/LACR/',
    status: 'Active',
    verified: '2026-09-12',
    tags: ['nsa', 'linux', 'access control', 'security'],
  },
];
