import type { Policy, Project, TimelineEvent } from './data';

const reviewed = '2026-09-12';

export const projectExpansion: Project[] = [
  {
    id: 'brl-cad',
    name: 'BRL-CAD',
    summary: 'A long-running constructive solid geometry modeling, editing, ray-tracing, and analysis system created by the U.S. Army and developed in the open since 2004.',
    sponsor: 'U.S. Army Research Laboratory',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: '3D modeling',
    license: 'LGPL-2.1 collective work; component-specific BSD/BDL/Public domain/third-party terms',
    repository: 'https://github.com/BRL-CAD/brlcad',
    officialUrl: 'https://brlcad.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: reviewed,
    tags: ['army', 'cad', 'geometry', 'modeling', 'simulation'],
  },
  {
    id: 'ghidra',
    name: 'Ghidra',
    summary: 'A software reverse-engineering framework developed by NSA Research and released publicly as open source in 2019.',
    sponsor: 'National Security Agency',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Software analysis',
    license: 'Apache-2.0 primary; GPL-3.0 support programs; federal portions Public domain; third-party terms',
    repository: 'https://github.com/NationalSecurityAgency/ghidra',
    officialUrl: 'https://www.nsa.gov/ghidra',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: reviewed,
    tags: ['nsa', 'cybersecurity', 'reverse engineering', 'analysis'],
  },
  {
    id: 'atak-civ',
    name: 'Android Tactical Assault Kit for Civilian Use (ATAK-CIV)',
    summary: 'The open source civilian edition of a government-owned geospatial situational-awareness platform; the record does not imply that every TAK product line is open source.',
    sponsor: 'TAK Product Center / Army DEVCOM C5ISR; Air Force Research Laboratory (origin)',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Situational awareness',
    license: 'GPL-3.0; qualifying U.S. federal portions Public domain',
    repository: 'https://github.com/TAK-Product-Center/atak-civ',
    officialUrl: 'https://tak.gov/pages/our-process',
    evidenceUrl: 'https://afresearchlab.com/tactical-assault-kit-tak/',
    status: 'Active',
    featured: true,
    verified: reviewed,
    tags: ['air force', 'geospatial', 'public safety', 'mobile'],
  },
  {
    id: 'hirs',
    name: 'HIRS',
    summary: 'An NSA proof-of-concept for trusted-computing provisioning, platform integrity reporting, and hardware attestation; its repository warns that it is not production-ready.',
    sponsor: 'NSA Cybersecurity',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Supply chain security',
    license: 'Apache-2.0 / Public domain',
    repository: 'https://github.com/nsacyber/HIRS',
    officialUrl: 'https://github.com/nsacyber/HIRS',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Reference',
    verified: reviewed,
    tags: ['nsa', 'hardware', 'attestation', 'tpm', 'experimental'],
  },
  {
    id: 'paccor',
    name: 'paccor',
    summary: 'NSA tooling for creating, signing, inspecting, and validating platform attribute certificates used in hardware and software supply-chain attestation.',
    sponsor: 'NSA Cybersecurity',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Supply chain security',
    license: 'Apache-2.0',
    repository: 'https://github.com/nsacyber/paccor',
    officialUrl: 'https://nsacyber.github.io/paccor/',
    status: 'Active',
    verified: reviewed,
    tags: ['nsa', 'hardware', 'attestation', 'certificates'],
  },
  {
    id: 'hootenanny',
    name: 'Hootenanny',
    summary: 'A machine-assisted map-conflation and schema-translation system funded by NGA, open-sourced in 2015, and used in government geospatial production.',
    sponsor: 'National Geospatial-Intelligence Agency',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'GPL-3.0',
    repository: 'https://github.com/ngageoint/hootenanny',
    officialUrl: 'https://github.com/ngageoint/hootenanny/blob/master/docs/overview/Introduction.asciidoc',
    status: 'Active',
    verified: reviewed,
    tags: ['nga', 'maps', 'conflation', 'geospatial'],
  },
  {
    id: 'mage',
    name: 'MAGE',
    summary: 'A mobile field-data collection and situational-awareness platform designed for low-bandwidth and disconnected environments.',
    sponsor: 'National Geospatial-Intelligence Agency',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Field data',
    license: 'Apache-2.0',
    repository: 'https://github.com/ngageoint/MAGE',
    officialUrl: 'https://www.nga.mil/assets/files/2024_MAGE_Fact_Sheet.pdf',
    evidenceUrl: 'https://github.com/ngageoint/MAGE',
    status: 'Active',
    verified: reviewed,
    tags: ['nga', 'mobile', 'geospatial', 'offline'],
  },
  {
    id: 'sarpy',
    name: 'SarPy',
    summary: 'An NGA-developed Python library for synthetic-aperture-radar and geospatial data; the repository is consolidating toward SARKit and flags legacy-reader deprecations for SarPy 2.0.',
    sponsor: 'National Geospatial-Intelligence Agency',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'MIT',
    repository: 'https://github.com/ngageoint/sarpy',
    officialUrl: 'https://github.com/ngageoint/sarpy',
    status: 'Active',
    verified: reviewed,
    tags: ['nga', 'radar', 'imagery', 'python'],
  },
  {
    id: 'nga-geopackage',
    name: 'NGA GeoPackage',
    summary: 'A suite of NGA software development kits for standards-based geospatial storage; the project remains available but is in maintenance mode.',
    sponsor: 'National Geospatial-Intelligence Agency',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'MIT',
    repository: 'https://github.com/ngageoint/GeoPackage',
    officialUrl: 'https://github.com/ngageoint/GeoPackage',
    status: 'Maintained',
    verified: reviewed,
    tags: ['nga', 'geopackage', 'sdk', 'maintenance mode'],
  },
  {
    id: 'apache-accumulo',
    name: 'Apache Accumulo',
    summary: 'A distributed sorted key-value store with cell-level security, begun at NSA in 2008 and transferred to independent Apache Software Foundation governance.',
    sponsor: 'Apache Software Foundation; National Security Agency (origin)',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Data infrastructure',
    license: 'Apache-2.0',
    repository: 'https://github.com/apache/accumulo',
    officialUrl: 'https://accumulo.apache.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    featured: true,
    verified: reviewed,
    tags: ['nsa', 'apache', 'database', 'security'],
  },
  {
    id: 'apache-nifi',
    name: 'Apache NiFi',
    summary: 'A secure dataflow automation platform that originated at NSA as NiagaraFiles and moved to independent Apache Software Foundation governance in 2014.',
    sponsor: 'Apache Software Foundation; National Security Agency (origin)',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Data integration',
    license: 'Apache-2.0',
    repository: 'https://github.com/apache/nifi',
    officialUrl: 'https://nifi.apache.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: reviewed,
    tags: ['nsa', 'apache', 'dataflow', 'provenance'],
  },
  {
    id: 'grass-gis',
    name: 'GRASS GIS',
    summary: 'A four-decade geospatial analysis platform created by the U.S. Army Corps of Engineers and now sustained as an OSGeo community project.',
    sponsor: 'OSGeo / NumFOCUS; U.S. Army CERL (origin)',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Geospatial',
    license: 'GPL-2.0-or-later',
    repository: 'https://github.com/OSGeo/grass',
    officialUrl: 'https://grass.osgeo.org/about/history/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: reviewed,
    tags: ['army corps', 'osgeo', 'gis', 'maps'],
  },
  {
    id: 'paraview',
    name: 'ParaView',
    summary: 'A distributed scientific-visualization application developed through collaboration among Kitware, national laboratories, the Department of Energy, and Army Research Laboratory.',
    sponsor: 'Kitware; DOE national laboratories and U.S. Army Research Laboratory collaborators',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Science & engineering',
    license: 'BSD-3-Clause',
    repository: 'https://gitlab.kitware.com/paraview/paraview',
    officialUrl: 'https://www.paraview.org/',
    evidenceUrl: 'https://code.mil/oss-faq.html',
    status: 'Active',
    verified: reviewed,
    tags: ['doe', 'army', 'visualization', 'science'],
  },
  {
    id: 'selinux',
    name: 'SELinux',
    summary: 'The userspace tools and libraries for the NSA-origin SELinux mandatory-access-control architecture, now maintained by the broader SELinux community.',
    sponsor: 'SELinux community; National Security Agency (origin)',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cybersecurity',
    license: 'Mixed, component-specific GPL-2.0/LGPL-2.1/Public domain/FreeBSD/third-party terms',
    repository: 'https://github.com/SELinuxProject/selinux',
    officialUrl: 'https://www.nsa.gov/Research/NSA-Mission-Oriented-Research/LACR/',
    status: 'Active',
    verified: reviewed,
    tags: ['nsa', 'linux', 'access control', 'security'],
  },
];

export const policyExpansion: Policy[] = [
  {
    id: 'dowi-8430-01', year: 2026, title: 'DoWI 8430.01 — Accelerated Mission Software',
    issuer: 'U.S. Department of Defense / Department of War', geography: 'United States', type: 'Departmental instruction', status: 'Current',
    summary: 'Prioritizes reuse, open source, shared repositories, software inventories, provenance, secure delivery, and public release of suitable government software under widely recognized licenses.',
    url: 'https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/843001p.PDF', reviewed,
  },
  {
    id: 'share-it-act', year: 2024, title: 'SHARE IT Act — Public Law 118-187',
    issuer: 'U.S. Congress', geography: 'United States', type: 'Law', status: 'Current',
    summary: 'Requires covered custom code and associated artifacts to be stored in a public or federal-accessible private repository, supported by government-wide reuse rights and public metadata; it does not require every project to be publicly released as open source.',
    url: 'https://www.congress.gov/118/plaws/publ187/PLAW-118publ187.pdf', reviewed,
  },
  {
    id: 'gsa-2107-1a', year: 2026, title: 'GSA Open Source Software Policy — CIO 2107.1A',
    issuer: 'U.S. General Services Administration', geography: 'United States', type: 'Agency policy', status: 'Current',
    summary: 'Establishes an open-first operating model in which new custom code is developed in publicly readable repositories unless an approved justification applies.',
    url: 'https://www.gsa.gov/directives-library/gsa-open-source-software-oss-policy-1', reviewed,
  },
  {
    id: 'cms-open-source-rules', year: 2026, title: 'Open Source Business Rules and Recommended Practices',
    issuer: 'Centers for Medicare & Medicaid Services', geography: 'United States', type: 'Implementation standard', status: 'Current',
    summary: 'Provides practical inbound and outbound OSS rules for licensing, approved sources, package management, security scans, documentation, code.json, governance, and release through CMS GitHub.',
    url: 'https://www.cms.gov/tra/Application_Development/AD_0230_Open_Source_Business_Rules.htm', reviewed,
  },
  {
    id: 'nasa-npr-2210-1e', year: 2023, title: 'NPR 2210.1E — Release of NASA Software',
    issuer: 'National Aeronautics and Space Administration', geography: 'United States', type: 'Procedural directive', status: 'Current',
    summary: 'Defines NASA’s end-to-end software release process, including invention disclosure, rights, export, security and releasability reviews, approval authorities, and open source as a release category.',
    url: 'https://nodis3.gsfc.nasa.gov/displayDir.cfm?c=2210&s=1E&t=NPR', reviewed,
  },
  {
    id: 'doe-order-241-1c', year: 2024, title: 'DOE Order 241.1C — Scientific and Technical Information Management',
    issuer: 'U.S. Department of Energy', geography: 'United States', type: 'Departmental order', status: 'Current',
    summary: 'Requires releasable scientific software to be reported with repository URL, license, developers, release date, intellectual-property or distribution limitations, and releasing official.',
    url: 'https://www.energy.gov/documents/scientific-and-technical-information-management', reviewed,
  },
  {
    id: 'omb-m-25-21', year: 2025, title: 'M-25-21 — Accelerating Federal Use of AI',
    issuer: 'U.S. Office of Management and Budget', geography: 'United States', type: 'Memorandum', status: 'Current',
    summary: 'Directs government-wide sharing of custom AI code, models, and weights and encourages public maintenance of AI code as open source where practicable, subject to defined legal and mission exceptions.',
    url: 'https://www.whitehouse.gov/wp-content/uploads/2025/02/M-25-21-Accelerating-Federal-Use-of-AI-through-Innovation-Governance-and-Public-Trust.pdf', reviewed,
  },
  {
    id: 'cisa-oss-roadmap', year: 2023, title: 'Open Source Software Security Roadmap',
    issuer: 'Cybersecurity and Infrastructure Security Agency', geography: 'United States', type: 'Roadmap', status: 'Current',
    summary: 'Sets CISA’s FY2024–FY2026 program for dependency and systemic-risk visibility, federal OSPO guidance, vulnerability reduction, and ecosystem hardening; recheck after the stated FY2026 horizon.',
    url: 'https://www.cisa.gov/sites/default/files/2024-02/CISA-Open-Source-Software-Security-Roadmap-508c.pdf', reviewed,
  },
  {
    id: 'nist-ssdf-1-1', year: 2022, title: 'NIST SP 800-218 — Secure Software Development Framework v1.1',
    issuer: 'National Institute of Standards and Technology', geography: 'United States', type: 'Technical standard', status: 'Current',
    summary: 'Defines technology-neutral secure development practices applicable to government-released code and open source consumption; version 1.1 remains final while version 1.2 is a draft.',
    url: 'https://csrc.nist.gov/pubs/sp/800/218/final', reviewed,
  },
  {
    id: 'dodi-5230-09', year: 2019, title: 'DoDI 5230.09 — Clearance of DoD Information for Public Release',
    issuer: 'U.S. Department of Defense', geography: 'United States', type: 'Public-release instruction', status: 'Current',
    summary: 'Provides the prepublication review framework used to prevent release of classified, export-controlled, or otherwise protected defense information, including material surrounding software releases.',
    url: 'https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/523009p.pdf', reviewed,
  },
  {
    id: 'dodi-5230-24', year: 2023, title: 'DoDI 5230.24 — Distribution Statements on DoD Technical Information',
    issuer: 'U.S. Department of Defense', geography: 'United States', type: 'Distribution instruction', status: 'Current',
    summary: 'Defines distribution markings for DoD technical information, explicitly including computer software and documentation; public release requires the appropriate clearance and distribution statement.',
    url: 'https://www.esd.whs.mil/portals/54/documents/dd/issuances/dodi/523024p.pdf', reviewed,
  },
  {
    id: 'usc-17-105', year: 1976, title: '17 U.S.C. § 105 — Subject matter of copyright: United States Government works',
    issuer: 'U.S. Congress', geography: 'United States', type: 'Statute', status: 'Current',
    summary: 'Provides the core rule that U.S. copyright protection is generally unavailable for federal government works; contractor code, mixed works, patents, foreign rights, and other restrictions require separate analysis.',
    url: 'https://uscode.house.gov/view.xhtml?req=%28title%3A17%20section%3A105%20edition%3Aprelim%29', reviewed,
  },
  {
    id: 'omb-m-04-16', year: 2004, title: 'M-04-16 — Software Acquisition',
    issuer: 'U.S. Office of Management and Budget', geography: 'United States', type: 'Memorandum', status: 'Reference',
    summary: 'A legacy federal acquisition memorandum stating that agencies should evaluate open source and proprietary software on merit and apply technology-neutral procurement requirements.',
    url: 'https://georgewbush-whitehouse.archives.gov/omb/memoranda/fy04/m04-16.html', reviewed,
  },
  {
    id: 'md-open-source-policy', year: 'Undated', title: 'Maryland Open Source Policy',
    issuer: 'Maryland Department of Information Technology', geography: 'Maryland', type: 'Administrative policy', status: 'Current',
    summary: 'Encourages public repositories, defines release checks for rights, privacy, credentials, dependency licenses and vulnerabilities, and defaults suitable state releases to MIT unless another OSI-compatible license fits better.',
    url: 'https://doit.maryland.gov/policies/Websites-and-Data/Pages/Maryland-Open-Source-Policy.aspx', reviewed,
  },
  {
    id: 'nh-rsa-21-r-11', year: 2012, title: 'RSA 21-R:11 — Use of Technology Solutions by State Agencies',
    issuer: 'New Hampshire General Court', geography: 'New Hampshire', type: 'Law', status: 'Current',
    summary: 'Requires executive agencies to compare proprietary and open source options on total cost and value, document the analysis, and avoid non-open standards where the statute specifies.',
    url: 'https://gc.nh.gov/rsa/html/I/21-R/21-R-11.htm', reviewed,
  },
  {
    id: 'ok-62-34-31-1', year: 2012, title: '62 O.S. § 34.31.1 — Software acquisition requests',
    issuer: 'Oklahoma Legislature', geography: 'Oklahoma', type: 'Law', status: 'Current',
    summary: 'Requires state software requests to consider whether proprietary or open source software is most cost-effective across acquisition, support, maintenance, and training, with an open-standards preference where possible.',
    url: 'https://www.oklegislature.gov/OK_Statutes/CompleteTitles/os62.pdf', reviewed,
  },
  {
    id: 'ut-r895-3', year: 2025, title: 'R895-3 — Computer Software Licensing, Copyright, Control, Retention, and License',
    issuer: 'Utah Department of Government Operations, Division of Technology Services', geography: 'Utah', type: 'Administrative rule', status: 'Current',
    summary: 'Establishes state ownership and contracting controls, requires CIO approval before an agency sells or licenses state-owned software, and requires dependency compatibility review for the chosen distribution method and license.',
    url: 'https://adminrules.utah.gov/api/public/getfile/uac-pdf/f6ece043-9bfe-4cc8-9abe-69238a042daa.pdf/R895-3.pdf', reviewed,
  },
  {
    id: 'ny-its-p19-005', year: 2020, title: 'ITS-P19-005 — Acceptable Use of Open-Source Software',
    issuer: 'New York State Office of Information Technology Services', geography: 'New York', type: 'Administrative policy', status: 'Current',
    summary: 'Governs state adoption of OSS through CTO or designee approval, publicly available source, legal review of licenses and terms, and approved-software and pre-screened-license lists; it addresses use rather than release of state-owned code.',
    url: 'https://its.ny.gov/acceptable-use-open-source-software', reviewed,
  },
  {
    id: 'wa-bridge-oss', year: 2025, title: 'Bridge Design Manual M 23-50.24 §1.3.10.A — Policy on Open Source Software',
    issuer: 'WSDOT Bridge and Structures Office', geography: 'Washington', type: 'Agency policy', status: 'Current',
    summary: 'Commits the Bridge and Structures Office to license its engineering software as open source and to prefer and promote OSS in the bridge-engineering community.',
    url: 'https://wsdot.wa.gov/publications/manuals/fulltext/M23-50/Chapter1.pdf', reviewed,
  },
  {
    id: 'ch-emota', year: 2023, title: 'Federal Act of 17 March 2023 on the Use of Electronic Means to Carry Out Official Tasks (EMOTA) — Article 9',
    issuer: 'Swiss Confederation', geography: 'Switzerland', type: 'Law', status: 'Current',
    summary: 'Prospectively requires covered federal authorities to publish software developed or materially further-developed after they entered Article 9’s scope, subject to third-party-rights, security, research, and funding exceptions; it does not retroactively require release of existing or uncustomized standard software.',
    url: 'https://www.fedlex.admin.ch/eli/cc/2023/682/en', reviewed,
  },
  {
    id: 'it-software-reuse', year: 2019, title: 'Linee guida su acquisizione e riuso di software per le pubbliche amministrazioni',
    issuer: 'Agency for Digital Italy', geography: 'Italy', type: 'Implementation guidance', status: 'Current',
    summary: 'Implements Digital Administration Code Articles 68–69 through acquisition review, commissioned-code ownership, and open publication with documentation, licensing, cataloging, maintenance, and reuse guidance, subject to national-security and related exceptions.',
    url: 'https://www.agid.gov.it/it/design-servizi/riuso-open-source/linee-guida-acquisizione-riuso-software-pa', reviewed,
  },
  {
    id: 'es-eni-software', year: 2010, title: 'Real Decreto 4/2010, de 8 de enero — National Interoperability Framework, Articles 16–17',
    issuer: 'Government of Spain', geography: 'Spain', type: 'Royal decree', status: 'Current',
    summary: 'Defines open-license freedoms, prefers the EUPL, requires procurement rights supporting reuse, and governs government application directories; source-publication details apply to finished products already declared open source. Articles 16–17 were amended effective 2 April 2021.',
    url: 'https://www.boe.es/buscar/act.php?id=BOE-A-2010-1331', reviewed,
  },
  {
    id: 'de-egovg-16a', year: 2024, title: 'E-Government Act § 16a — Open Source',
    issuer: 'Federal Republic of Germany', geography: 'Germany', type: 'Law', status: 'Current',
    summary: 'Provides that federal authorities should give priority, when newly acquiring software, to software with public source and licenses permitting use, redistribution, and modification.',
    url: 'https://www.gesetze-im-internet.de/egovg/__16a.html', reviewed,
  },
  {
    id: 'uy-law-19179', year: 2013, title: 'Law No. 19.179 — Free software and open formats in government',
    issuer: 'Oriental Republic of Uruguay', geography: 'Uruguay', type: 'Law', status: 'Current',
    summary: 'Requires covered state bodies to prefer free software, justify proprietary choices, use open formats, and license state-developed or contracted software as free software when it is distributed.',
    url: 'https://www.impo.com.uy/bases/leyes/19179-2013', reviewed,
  },
  {
    id: 'uy-decree-44-015', year: 2015, title: 'Decree No. 44/015 — Regulation of Law No. 19.179',
    issuer: 'Oriental Republic of Uruguay', geography: 'Uruguay', type: 'Regulation', status: 'Current',
    summary: 'Implements Uruguay’s free-software law through planning, public-catalog checks, migration requirements, and AGESIC procedures for justifying exceptions.',
    url: 'https://www.impo.com.uy/bases/decretos/44-2015', reviewed,
  },
  {
    id: 'in-oss-adoption', year: 2015, title: 'Policy on Adoption of Open Source Software for Government of India',
    issuer: 'Government of India, MeitY', geography: 'India', type: 'National policy', status: 'Current',
    summary: 'Says covered central-government bodies shall endeavour to prefer OSS for new e-government systems and versions and document exclusions; states may opt into the policy.',
    url: 'https://egovstandards.gov.in/sites/default/files/2021-07/Notification%20of%20Policy%20on%20Adoption%20of%20Open%20Source%20Software%20for%20Government%20of%20India_0.pdf', reviewed,
  },
  {
    id: 'in-source-open', year: 2015, title: 'Policy On Collaborative Application Development by Opening the Source Code of Government Applications',
    issuer: 'Government of India, MeitY', geography: 'India', type: 'National policy', status: 'Current',
    summary: 'Creates a framework for archiving custom government code and opening repositories for reuse and collaborative development, with security, strategic, and commercial-software exclusions.',
    url: 'https://www.meity.gov.in/sites/upload_files/dit/files/policy_government_application.pdf', reviewed,
  },
  {
    id: 'ec-software-reuse', year: 2021, title: 'Commission Decision 2021/C 495 I/01 on open source licensing and reuse of Commission software',
    issuer: 'European Commission', geography: 'European Union', type: 'Commission decision', status: 'Current',
    summary: 'Creates a procedure for software the Commission chooses to release, with repository, license, rights, and exception checks; it creates no public right to demand release and no duty to update, support, or continue development. Monitor for the required review result.',
    url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32021D1209%2801%29', reviewed,
  },
  {
    id: 'ca-enterprise-architecture', year: 2025, title: 'Government of Canada Enterprise Architecture Framework',
    issuer: 'Treasury Board of Canada Secretariat', geography: 'Canada', type: 'Architecture framework', status: 'Current',
    summary: 'Sets architecture-review criteria to reuse before building, prefer open source solutions, contribute improvements upstream, register OSS, and publish reusable enterprise components openly.',
    url: 'https://www.canada.ca/en/government/system/digital-government/policies-standards/government-canada-enterprise-architecture-framework.html', reviewed,
  },
  {
    id: 'nzgoal-se', year: 2016, title: 'NZGOAL Software Extension — Version 1',
    issuer: 'New Zealand Government', geography: 'New Zealand', type: 'Implementation guidance', status: 'Current',
    summary: 'Voluntary guidance strongly encouraging agencies to apply a five-stage release tree to agency-owned software: rights, exceptions, license selection, license application, and release.',
    url: 'https://www.data.govt.nz/toolkit/policies/nzgoal/nzgoal-se', reviewed,
  },
  {
    id: 'nl-open-unless', year: 2020, title: 'Release of government software source code — “Open, unless”',
    issuer: 'Netherlands Ministry of the Interior and Kingdom Relations', geography: 'Netherlands', type: 'Policy letter', status: 'Current',
    summary: 'States a nonbinding “open, unless” policy principle that government software should be released as open source unless a substantiated reason prevents it.',
    url: 'https://www.rijksoverheid.nl/documenten/2020/04/17/kamerbrief-inzake-vrijgeven-broncode-overheidssoftware', reviewed,
  },
  {
    id: 'un-global-digital-compact', year: 2024, title: 'Global Digital Compact',
    issuer: 'United Nations General Assembly', geography: 'Global', type: 'Intergovernmental commitment', status: 'Current',
    summary: 'A nonbinding political commitment through 2030 to develop, disseminate, and maintain safe and secure open source software and to promote open standards and interoperability.',
    url: 'https://docs.un.org/a/res/79/1', reviewed,
  },
  {
    id: 'unesco-open-science', year: 2021, title: 'Recommendation on Open Science',
    issuer: 'UNESCO General Conference', geography: 'Global', type: 'Intergovernmental recommendation', status: 'Current',
    summary: 'A nonbinding open-science recommendation that publicly funded research outputs, including software and source code, be openly licensed or dedicated to the public domain with documentation and proportionate exceptions.',
    url: 'https://www.unesco.org/en/legal-affairs/recommendation-open-science', reviewed,
  },
  {
    id: 'au-digital-reuse', year: 2021, title: 'Digital and ICT Reuse Policy',
    issuer: 'Australian Digital Transformation Agency', geography: 'Australia', type: 'Whole-of-government policy', status: 'Current',
    summary: 'Requires covered Commonwealth entities to reuse digital assets where possible, design and build for reuse, and share created assets unless there is a substantiated reason not to; an announced 2026 revision warrants early re-review.',
    url: 'https://architecture.digital.gov.au/policy/digital-and-ict-reuse-policy', reviewed,
  },
  {
    id: 'br-law-14063', year: 2020, title: 'Law No. 14.063 — Article 16',
    issuer: 'Federative Republic of Brazil', geography: 'Brazil', type: 'Law', status: 'Current',
    summary: 'Requires covered systems developed exclusively by public bodies to use an open-code license, subject to secrecy, data, third-party-component, and pre-existing-contract exceptions; reuse rights are framed primarily for public entities.',
    url: 'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2020/lei/l14063.htm', reviewed,
  },
  {
    id: 'un-open-source-principles', year: 2025, title: 'United Nations Open Source Principles',
    issuer: 'UN Chief Executives Board Digital Technology Network', geography: 'Global', type: 'Institutional principles', status: 'Current',
    summary: 'Sets eight voluntary operating principles: open by default, contribute back, secure by design, inclusive participation, reuse, documentation, contributor support, and sustainability.',
    url: 'https://opensource.un.org/en/news/united-nations-open-source-principles', reviewed,
  },
  {
    id: 'un-common-policy-framework', year: 2024, title: 'Open Source United — Common Policy Framework, Release Candidate 1.0',
    issuer: 'United Nations Open Source United', geography: 'Global', type: 'Draft framework', status: 'Reference',
    summary: 'An evolving, nonbinding maturity framework covering procurement, custom-code release, governance, licensing, security, catalogs, sustainability, archiving, and measurement.',
    url: 'https://opensource.un.org/sites/default/files/2026-01/open_source_united_-_common_policy_framework_rc1.pdf', reviewed,
  },
  {
    id: 'za-foss-policy', year: 2007, title: 'Policy on Free and Open Source Software Use for the South African Government',
    issuer: 'South African Department of Public Service and Administration', geography: 'South Africa', type: 'Cabinet policy', status: 'Reference',
    summary: 'Sets a FOSS-first direction, requires justification for proprietary selection, encourages migration where comparable FOSS exists, and supports FOSS licensing for newly developed government software; current force is not affirmatively reconfirmed.',
    url: 'https://www.dpsa.gov.za/dpsa2g/documents/ogcio/2007/FOSS_OC%20POLICY_2006_APPENDIX%20A.pdf', reviewed,
  },
];

export const timelineExpansion: TimelineEvent[] = [
  { year: '2004', title: 'BRL-CAD becomes an open source project', body: 'The Army-origin modeling system opens its development after decades of government use.', projectId: 'brl-cad' },
  { year: '2007', title: 'South Africa adopts a government FOSS policy', body: 'Cabinet policy establishes a FOSS-first direction and a justification test for proprietary choices.', policyId: 'za-foss-policy' },
  { year: '2011', title: 'Accumulo moves into Apache governance', body: 'The NSA-origin database enters the Apache Incubator on its path to independent foundation stewardship.', projectId: 'apache-accumulo' },
  { year: '2014', title: 'NiagaraFiles becomes Apache NiFi', body: 'NSA contributes its dataflow technology to the Apache Software Foundation for public governance.', projectId: 'apache-nifi' },
  { year: '2015', title: 'India adopts twin open source policies', body: 'National policy gives OSS preference in e-government and creates a framework for collaborative release of government applications.', policyId: 'in-oss-adoption' },
  { year: '2019', title: 'NSA releases Ghidra', body: 'A mission-developed reverse-engineering framework becomes one of the most visible U.S. government open source releases.', projectId: 'ghidra' },
  { year: '2020', title: 'ATAK-CIV opens its source', body: 'The civilian edition of the government-owned situational-awareness platform is released publicly.', projectId: 'atak-civ' },
  { year: '2021', title: 'European Commission standardizes software release', body: 'A formal decision defines how Commission-owned software is cleared, licensed, and published.', policyId: 'ec-software-reuse' },
  { year: '2023', title: 'Switzerland enacts a prospective federal publication duty', body: 'EMOTA Article 9 requires covered authorities to publish newly developed or materially extended software after they enter scope, subject to defined exceptions.', policyId: 'ch-emota' },
  { year: '2024', title: 'The SHARE IT Act becomes law', body: 'Federal custom code gains statutory repository, reuse-rights, metadata, and agency-policy requirements—without making every repository public.', policyId: 'share-it-act' },
  { year: '2026', title: 'DoD issues accelerated mission software policy', body: 'A new department-wide instruction connects reuse, open source, provenance, secure delivery, inventories, and public release.', policyId: 'dowi-8430-01' },
];

export const officialSourceExpansion = [
  { label: 'U.S. Congress', url: 'https://www.congress.gov/', note: 'Federal laws, bill text, actions, and public-law publications' },
  { label: 'NASA NODIS', url: 'https://nodis3.gsfc.nasa.gov/', note: 'Current NASA directives, requirements, and software-release procedure' },
  { label: 'CISA OSS Roadmap', url: 'https://www.cisa.gov/sites/default/files/2024-02/CISA-Open-Source-Software-Security-Roadmap-508c.pdf', note: 'Federal open source software security priorities and guidance' },
  { label: 'Maryland DoIT', url: 'https://doit.maryland.gov/policies/Websites-and-Data/Pages/Maryland-Open-Source-Policy.aspx', note: 'State-level open source publication policy and release checklist' },
  { label: 'Swiss Fedlex', url: 'https://www.fedlex.admin.ch/eli/cc/2023/682/en', note: 'Official federal act with open source publication requirements' },
  { label: 'Developers Italia', url: 'https://developers.italia.it/', note: 'Italian public software catalog, reuse guidance, and release tooling' },
  { label: 'New Zealand NZGOAL-SE', url: 'https://www.data.govt.nz/toolkit/policies/nzgoal/nzgoal-se', note: 'Government software rights and release decision framework' },
];
