import { officialSourceExpansion, policyExpansion, projectExpansion, timelineExpansion } from './catalog-expansion';

export type Jurisdiction = 'U.S. federal' | 'U.S. state' | 'International';

export type Project = {
  id: string;
  name: string;
  summary: string;
  sponsor: string;
  geography: string;
  jurisdiction: Jurisdiction;
  domain: string;
  license: string;
  repository: string;
  officialUrl: string;
  evidenceUrl?: string;
  status: 'Active' | 'Maintained' | 'Reference';
  featured?: boolean;
  verified: string;
  tags: string[];
};

export const projects: Project[] = [
  {
    id: 'uswds',
    name: 'U.S. Web Design System',
    summary: 'Accessible components, design tokens, and guidance for trustworthy federal digital services.',
    sponsor: 'General Services Administration',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Design systems',
    license: 'Public domain / CC0',
    repository: 'https://github.com/uswds/uswds',
    officialUrl: 'https://designsystem.digital.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['accessibility', 'design', 'web'],
  },
  {
    id: 'login-gov',
    name: 'Login.gov',
    summary: 'A shared sign-in service that gives the public simple, secure access to participating U.S. government programs.',
    sponsor: 'General Services Administration',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Digital identity',
    license: 'Public domain / CC0',
    repository: 'https://github.com/18F/identity-idp',
    officialUrl: 'https://www.login.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['identity', 'security', 'shared service'],
  },
  {
    id: 'cloud-gov',
    name: 'cloud.gov',
    summary: 'A secure, compliant platform that helps U.S. agencies deliver applications without rebuilding cloud infrastructure.',
    sponsor: 'General Services Administration',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cloud platform',
    license: 'Public domain / CC0',
    repository: 'https://github.com/cloud-gov',
    officialUrl: 'https://cloud.gov/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['cloud', 'platform', 'security'],
  },
  {
    id: 'code-gov',
    name: 'Code.gov',
    summary: 'The federal source-code policy program and public inventory work created to improve discoverability and reuse.',
    sponsor: 'General Services Administration',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Code inventory',
    license: 'Public domain',
    repository: 'https://github.com/GSA/code-gov',
    officialUrl: 'https://code.gov/',
    status: 'Reference',
    verified: '2026-09-03',
    tags: ['inventory', 'policy', 'reuse'],
  },
  {
    id: 'oscal',
    name: 'OSCAL',
    summary: 'Machine-readable formats from NIST for expressing system security controls, assessments, and plans.',
    sponsor: 'National Institute of Standards and Technology',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Cybersecurity',
    license: 'Public domain',
    repository: 'https://github.com/usnistgov/OSCAL',
    officialUrl: 'https://pages.nist.gov/OSCAL/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['security', 'standards', 'compliance'],
  },
  {
    id: 'openmdao',
    name: 'OpenMDAO',
    summary: 'A NASA-developed multidisciplinary design, analysis, and optimization framework for complex engineering systems.',
    sponsor: 'National Aeronautics and Space Administration',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Science & engineering',
    license: 'Apache-2.0',
    repository: 'https://github.com/OpenMDAO/OpenMDAO',
    officialUrl: 'https://openmdao.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['aerospace', 'optimization', 'science'],
  },
  {
    id: 'energyplus',
    name: 'EnergyPlus',
    summary: 'A whole-building energy simulation engine maintained with support from the U.S. Department of Energy.',
    sponsor: 'Department of Energy',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Climate & energy',
    license: 'BSD-3-Clause',
    repository: 'https://github.com/NREL/EnergyPlus',
    officialUrl: 'https://energyplus.net/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['buildings', 'energy', 'simulation'],
  },
  {
    id: 'vets-api',
    name: 'VA.gov Vets API',
    summary: 'The API platform that powers veteran-facing services and integrations across VA.gov.',
    sponsor: 'Department of Veterans Affairs',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Public benefits',
    license: 'CC0-1.0',
    repository: 'https://github.com/department-of-veterans-affairs/vets-api',
    officialUrl: 'https://developer.va.gov/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['veterans', 'api', 'benefits'],
  },
  {
    id: 'code-mil',
    name: 'Code.mil',
    summary: 'The Department of Defense initiative for open collaboration and guidance around releasing government code.',
    sponsor: 'Department of Defense',
    geography: 'United States',
    jurisdiction: 'U.S. federal',
    domain: 'Code inventory',
    license: 'Public domain / OSI licenses',
    repository: 'https://github.com/Code-dot-mil',
    officialUrl: 'https://code.mil/',
    status: 'Maintained',
    featured: true,
    verified: '2026-09-03',
    tags: ['defense', 'policy', 'collaboration'],
  },
  {
    id: 'ca-design-system',
    name: 'California Design System',
    summary: 'Reusable patterns and components for consistent, accessible State of California digital services.',
    sponsor: 'California Department of Technology',
    geography: 'California',
    jurisdiction: 'U.S. state',
    domain: 'Design systems',
    license: 'Apache-2.0',
    repository: 'https://github.com/cagov/design-system',
    officialUrl: 'https://designsystem.webstandards.ca.gov/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['california', 'accessibility', 'design'],
  },
  {
    id: 'mayflower',
    name: 'Mayflower',
    summary: 'The component library and pattern system created for Mass.gov digital products.',
    sponsor: 'Commonwealth of Massachusetts',
    geography: 'Massachusetts',
    jurisdiction: 'U.S. state',
    domain: 'Design systems',
    license: 'MIT',
    repository: 'https://github.com/massgov/mayflower',
    officialUrl: 'https://mayflower.digital.mass.gov/',
    status: 'Maintained',
    verified: '2026-09-03',
    tags: ['massachusetts', 'design', 'web'],
  },
  {
    id: 'govuk-design-system',
    name: 'GOV.UK Design System',
    summary: 'A mature library of styles, components, and patterns used to build consistent UK public services.',
    sponsor: 'UK Government Digital Service',
    geography: 'United Kingdom',
    jurisdiction: 'International',
    domain: 'Design systems',
    license: 'MIT',
    repository: 'https://github.com/alphagov/govuk-frontend',
    officialUrl: 'https://design-system.service.gov.uk/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['united kingdom', 'design', 'accessibility'],
  },
  {
    id: 'govuk-notify',
    name: 'GOV.UK Notify',
    summary: 'A reusable notification service for public-sector email, text messages, and letters.',
    sponsor: 'UK Government Digital Service',
    geography: 'United Kingdom',
    jurisdiction: 'International',
    domain: 'Communications',
    license: 'MIT',
    repository: 'https://github.com/alphagov/notifications-api',
    officialUrl: 'https://www.notifications.service.gov.uk/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['united kingdom', 'notifications', 'shared service'],
  },
  {
    id: 'x-road',
    name: 'X-Road',
    summary: 'The secure data exchange layer established by Estonia and Finland and now reused internationally.',
    sponsor: 'Estonia & Finland / NIIS',
    geography: 'Estonia',
    jurisdiction: 'International',
    domain: 'Data exchange',
    license: 'MIT',
    repository: 'https://github.com/nordic-institute/X-Road',
    officialUrl: 'https://x-road.global/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['estonia', 'finland', 'interoperability'],
  },
  {
    id: 'formsg',
    name: 'FormSG',
    summary: 'A secure form builder built and maintained by Singapore’s Open Government Products team.',
    sponsor: 'Government Technology Agency of Singapore',
    geography: 'Singapore',
    jurisdiction: 'International',
    domain: 'Forms & workflows',
    license: 'MIT',
    repository: 'https://github.com/opengovsg/FormSG',
    officialUrl: 'https://form.gov.sg/',
    status: 'Active',
    featured: true,
    verified: '2026-09-03',
    tags: ['singapore', 'forms', 'productivity'],
  },
  {
    id: 'openfisca',
    name: 'OpenFisca',
    summary: 'A rules-as-code engine initiated in France for modeling taxes and benefits as testable software.',
    sponsor: 'French Interministerial Digital Directorate',
    geography: 'France',
    jurisdiction: 'International',
    domain: 'Rules as code',
    license: 'AGPL-3.0',
    repository: 'https://github.com/openfisca/openfisca-core',
    officialUrl: 'https://openfisca.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['france', 'benefits', 'policy'],
  },
  {
    id: 'decidim',
    name: 'Decidim',
    summary: 'A participatory democracy platform initiated by Barcelona and governed as a digital public commons.',
    sponsor: 'Barcelona City Council',
    geography: 'Spain',
    jurisdiction: 'International',
    domain: 'Civic participation',
    license: 'AGPL-3.0',
    repository: 'https://github.com/decidim/decidim',
    officialUrl: 'https://decidim.org/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['spain', 'democracy', 'participation'],
  },
  {
    id: 'gc-notify',
    name: 'GC Notify',
    summary: 'Canada’s government notification service for sending reliable email and text messages at scale.',
    sponsor: 'Canadian Digital Service',
    geography: 'Canada',
    jurisdiction: 'International',
    domain: 'Communications',
    license: 'MIT',
    repository: 'https://github.com/cds-snc/notification-api',
    officialUrl: 'https://notification.canada.ca/',
    status: 'Active',
    verified: '2026-09-03',
    tags: ['canada', 'notifications', 'shared service'],
  },
];

projects.push(...projectExpansion);

export type Policy = {
  id: string;
  year: number | 'Undated';
  title: string;
  issuer: string;
  geography: string;
  type: string;
  status: 'Current' | 'Reference' | 'Superseded';
  summary: string;
  url: string;
  reviewed: string;
};

export const policies: Policy[] = [
  {
    id: 'm-16-21',
    year: 2016,
    title: 'Federal Source Code Policy (M-16-21)',
    issuer: 'U.S. Office of Management and Budget',
    geography: 'United States',
    type: 'Memorandum',
    status: 'Current',
    summary: 'Establishes government-wide source-code reuse and the three-year open source pilot that led to Code.gov; the pilot period elapsed, while the broader reuse and publication direction remains operative.',
    url: 'https://www.whitehouse.gov/wp-content/uploads/legacy_drupal_files/omb/memoranda/2016/m_16_21.pdf',
    reviewed: '2026-09-12',
  },
  {
    id: 'dod-2022',
    year: 2022,
    title: 'Software Development and Open Source Software',
    issuer: 'U.S. Department of Defense CIO',
    geography: 'United States',
    type: 'Policy memorandum',
    status: 'Current',
    summary: 'Directs an Adopt, Buy, Create approach and sets open-by-default expectations for non-national-security software.',
    url: 'https://dodcio.defense.gov/Portals/0/Documents/Library/SoftwareDev-OpenSource.pdf',
    reviewed: '2026-09-03',
  },
  {
    id: 'ca-sam-4984',
    year: 2018,
    title: 'Open Source and Code Reuse Policy — SAM 4984.1',
    issuer: 'State of California',
    geography: 'California',
    type: 'Administrative policy',
    status: 'Current',
    summary: 'Requires code inventories and statewide reuse, and directs agencies to secure rights for public open source release when possible.',
    url: 'https://www.dgs.ca.gov/Resources/SAM/TOC/4900/4984-1',
    reviewed: '2026-09-03',
  },
  {
    id: 'uk-open-source',
    year: 2017,
    title: 'Be open and use open source',
    issuer: 'UK Government Digital Service',
    geography: 'United Kingdom',
    type: 'Implementation guidance',
    status: 'Current',
    summary: 'Explains how programs should consider open source and publish code openly under the Technology Code of Practice.',
    url: 'https://www.gov.uk/guidance/be-open-and-use-open-source',
    reviewed: '2026-09-03',
  },
  {
    id: 'fr-digital-republic',
    year: 2016,
    title: 'Law for a Digital Republic',
    issuer: 'French Republic',
    geography: 'France',
    type: 'Law',
    status: 'Current',
    summary: 'Recognizes administrative source code as a communicable public document and frames approved reuse licensing.',
    url: 'https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000033202746',
    reviewed: '2026-09-03',
  },
  {
    id: 'eu-open-source',
    year: 2026,
    title: 'EU Open Source Strategy',
    issuer: 'European Commission',
    geography: 'European Union',
    type: 'Strategy',
    status: 'Current',
    summary: 'Sets direction for stronger open digital ecosystems, public-sector reuse, sustainability, and European technological capacity.',
    url: 'https://digital-strategy.ec.europa.eu/en/policies/open-source-strategy',
    reviewed: '2026-09-03',
  },
  {
    id: 'interoperable-europe',
    year: 2024,
    title: 'Interoperable Europe Act',
    issuer: 'European Union',
    geography: 'European Union',
    type: 'Regulation',
    status: 'Current',
    summary: 'Creates a cooperation framework and encourages sharing and reuse of interoperability solutions across public administrations.',
    url: 'https://eur-lex.europa.eu/eli/reg/2024/903/oj',
    reviewed: '2026-09-03',
  },
  {
    id: 'osi-licenses',
    year: 1998,
    title: 'OSI Approved Licenses',
    issuer: 'Open Source Initiative',
    geography: 'Global',
    type: 'License standard',
    status: 'Current',
    summary: 'The directory’s canonical eligibility reference for licenses that meet the Open Source Definition.',
    url: 'https://opensource.org/licenses',
    reviewed: '2026-09-03',
  },
];

policies.push(...policyExpansion);

export type TimelineEvent = {
  year: string;
  title: string;
  body: string;
  projectId?: string;
  policyId?: string;
};

export const timeline: TimelineEvent[] = [
  { year: '1998', title: 'Open Source Definition becomes the common license test', body: 'OSI establishes a durable, public standard for software freedom and approved licenses.', policyId: 'osi-licenses' },
  { year: '2001', title: 'Estonia launches X-Road', body: 'A national data exchange foundation becomes a long-running example of reusable public infrastructure.', projectId: 'x-road' },
  { year: '2011', title: 'UK policy shifts toward open delivery', body: 'Government digital practice makes open source and code publication part of mainstream service delivery.' },
  { year: '2016', title: 'The U.S. publishes M-16-21', body: 'The Federal Source Code Policy creates a government-wide reuse policy and open source pilot.', policyId: 'm-16-21' },
  { year: '2016', title: 'France passes the Digital Republic law', body: 'Administrative source code is recognized within the public-document and reuse framework.', policyId: 'fr-digital-republic' },
  { year: '2017', title: 'Code.mil opens a defense collaboration path', body: 'The initiative invites public collaboration around DoD open source projects and licensing.', projectId: 'code-mil' },
  { year: '2018', title: 'California establishes statewide code reuse policy', body: 'State agencies receive inventory, reuse, and open publication requirements.', policyId: 'ca-sam-4984' },
  { year: '2022', title: 'DoD adopts open-by-default guidance', body: 'New policy clarifies open source use, contribution, and release across the department.', policyId: 'dod-2022' },
  { year: '2024', title: 'Interoperable Europe Act enters into force', body: 'European public administrations gain a shared legal framework for interoperable solutions.', policyId: 'interoperable-europe' },
  { year: '2026', title: 'European Commission refreshes open source strategy', body: 'The Commission links public-sector reuse, digital commons, and strategic technology capacity.', policyId: 'eu-open-source' },
];

timeline.push(...timelineExpansion);
timeline.sort((left, right) => Number(left.year) - Number(right.year));

export const glossary = [
  { term: 'Code inventory', definition: 'A machine-readable or human-readable catalog of software owned, commissioned, or maintained by an organization.' },
  { term: 'Copyleft', definition: 'A license approach that requires some redistributed modifications or derivative works to remain under the same or a compatible open license.' },
  { term: 'Digital public good', definition: 'Open software, data, AI models, standards, or content designed to advance public benefit and meet defined safeguards.' },
  { term: 'Fork', definition: 'A copy of a repository that can be developed independently while preserving a path to exchange improvements.' },
  { term: 'Open source', definition: 'Software whose license meets the Open Source Definition, including rights to use, study, modify, and redistribute the code.' },
  { term: 'OSPO', definition: 'An Open Source Program Office: a team that coordinates open source policy, compliance, publication, contribution, and community practice.' },
  { term: 'Permissive license', definition: 'An open source license with minimal redistribution conditions, such as MIT, BSD, or Apache-2.0.' },
  { term: 'Public code', definition: 'Software developed for public purposes that is made openly available with the legal and technical conditions needed for reuse.' },
  { term: 'Public domain', definition: 'Works not protected by copyright, or dedicated so broadly that anyone may use them without copyright restrictions.' },
  { term: 'SBOM', definition: 'A Software Bill of Materials: a structured list of components and dependencies contained in a software product.' },
  { term: 'Source available', definition: 'Code that can be viewed but whose license may restrict use, modification, or redistribution; it is not necessarily open source.' },
  { term: 'SPDX identifier', definition: 'A short, standardized expression used to identify a software license, such as MIT or Apache-2.0.' },
];

export const officialSources = [
  { label: 'Code.gov', url: 'https://code.gov/', note: 'U.S. federal source-code policy and inventory program' },
  { label: 'Code.mil', url: 'https://code.mil/', note: 'U.S. defense open source guidance and projects' },
  { label: 'California Open Source Portal', url: 'https://code.ca.gov/', note: 'State code-sharing and collaboration portal' },
  { label: 'code.gouv.fr', url: 'https://code.gouv.fr/', note: 'French public source-code and free-software program' },
  { label: 'openCode', url: 'https://opencode.de/', note: 'German public-administration software platform' },
  { label: 'OSI license list', url: 'https://opensource.org/licenses', note: 'Canonical license eligibility reference' },
];

officialSources.push(...officialSourceExpansion);
